## 00. PyTorch fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

Video: https://www.youtube.com/watch?v=V_xro1bcAuA&t=53215s


In [2]:
# Import libraries

import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu124


## Introduction to Tensors

### Creating tensors

PyTorch tensors are created using `torch.tensor()`

Doc: https://pytorch.org/docs/stable/tensors.html

In [3]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [7]:
# How many dimensions?
scalar.ndim

0

In [9]:
# Get the tensor's content (returns a regular integer)
scalar.item()

7

In [10]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [11]:
vector.ndim  # number of closing square brackets in the tensor's definition

1

In [12]:
vector.shape  # two by one elements

torch.Size([2])

In [14]:
# MATRIX
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [15]:
MATRIX.ndim

2

In [16]:
MATRIX.shape

torch.Size([2, 2])

In [17]:
# Index on matrix
MATRIX[0]

tensor([7, 8])

In [18]:
MATRIX[1]

tensor([ 9, 10])

In [19]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [20]:
TENSOR.ndim

3

In [21]:
TENSOR.shape  # 1 -> external pair of brackets

torch.Size([1, 3, 3])

In [24]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

--> 14. Creating random tensors in PyTorch (1:35:36)