## 00. PyTorch fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

Video: https://www.youtube.com/watch?v=V_xro1bcAuA&t=53215s


In [109]:
# Import libraries

import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu124


## Introduction to Tensors

### Creating tensors

PyTorch tensors are created using `torch.tensor()`

Doc: https://pytorch.org/docs/stable/tensors.html

In [110]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [111]:
# How many dimensions?
scalar.ndim

0

In [112]:
# Get the tensor's content (returns a regular integer)
scalar.item()

7

In [113]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [114]:
vector.ndim  # number of closing square brackets in the tensor's definition

1

In [115]:
vector.shape  # two by one elements

torch.Size([2])

In [116]:
# MATRIX
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [117]:
MATRIX.ndim

2

In [118]:
MATRIX.shape

torch.Size([2, 2])

In [119]:
# Index on matrix
MATRIX[0]

tensor([7, 8])

In [120]:
MATRIX[1]

tensor([ 9, 10])

In [121]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [122]:
TENSOR.ndim

3

In [123]:
TENSOR.shape  # 1 -> external pair of brackets

torch.Size([1, 3, 3])

In [124]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Creating random tensors in PyTorch

Random tensors are important because the way neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

In [125]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.6983, 0.2511, 0.2321, 0.1383],
        [0.5890, 0.6124, 0.0441, 0.9791],
        [0.5507, 0.6899, 0.6983, 0.3557]])

In [126]:
random_tensor.ndim

2

In [127]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3))  # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeroes and ones

In [128]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [129]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [130]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [131]:
# Data type
ones.dtype

torch.float32

### Create a range of tensors and tensors-like

In [132]:
# Use torch.arange() -> torch.range() deprecated
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [133]:
# Creating tensors-like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch and Deep Learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [134]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [135]:
float_32_tensor.dtype

torch.float32

In [136]:
# Float 16 tensor
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16)
float_16_tensor.dtype

torch.float16

In [137]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,           # what dataype is the tensor (e.g. float32 or float16)
                               device=None,          # what device the tensor is on (CPU or GPU)
                               requires_grad=False)  # whether or not to track the gradients with this tensor's operations

In [138]:
# Change a tensor's datatype
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [139]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

In [140]:
# Create a 32-bit integer tensor
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [141]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors

1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device rom a tensor, can use `tensor.device`

In [142]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.5502, 0.7875, 0.3773, 0.3393],
        [0.2695, 0.4049, 0.0026, 0.4018],
        [0.1885, 0.5615, 0.9917, 0.0940]])

In [143]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.5502, 0.7875, 0.3773, 0.3393],
        [0.2695, 0.4049, 0.0026, 0.4018],
        [0.1885, 0.5615, 0.9917, 0.0940]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [144]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [145]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [146]:
# Substract 10
tensor - 10

tensor([-9, -8, -7])

In [147]:
# Try out PyTorch inbuilt functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [148]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:

* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work

2. The resulting matrix has the shape of the **outer dimensions**:

* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`  

In [149]:
torch.matmul(torch.rand(2, 3), torch.rand(3, 2))

tensor([[0.5828, 0.9655],
        [0.9196, 1.2724]])

In [150]:
# Element-wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [151]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [152]:
tensor @ tensor

tensor(14)

In [153]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [154]:
# How long does it take?
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 2 ms, sys: 0 ns, total: 2 ms
Wall time: 1.87 ms


In [155]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 146 µs, sys: 0 ns, total: 146 µs
Wall time: 157 µs


tensor(14)

### One of the most common errors in deep learning: shape errors

In [156]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

In [157]:
#torch.mm(tensor_A, tensor_B)  # torch.mm is the same as torch.matmul(it's an alias for writing less code)

In [158]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [159]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [160]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [161]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print(f"Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, ... (tensor aggregation)

In [162]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [163]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [164]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [165]:
# Find the mean - note: the torch.mean() requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [166]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

In [167]:
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [168]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where minimum value occurs
x.argmin()

tensor(0)

In [169]:
x[0]

tensor(1)

In [170]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [171]:
x[9]

tensor(91)

## Reshaping, stacking, squeezing and unsqueezing tensors

- Reshaping - reshapes an input tensor to a defined shape  
- View - return a view of an input tensor of a certain shape but keep the same memory as the original tensor  
- Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
- Squeeze - removes all `1` dimensions from a tensor
- Unsqueeze - adds a `1` dimension to a target tensor
- Permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [172]:
# Create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [173]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [174]:
# Add an extra dimension
#x_reshaped = x.reshape(9, 1)
#x_reshaped, x_reshaped.shape

In [175]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [176]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [177]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [178]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [179]:
# Squeeze - remove all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [180]:
# Unsqueeze - add a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze to dim 0
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew target: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

# Add an extra dimension with unsqueeze to dim 1
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f"\nNew target: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New target: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])

New target: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape: torch.Size([9, 1])


In [181]:
# Permute - rearrange the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3))  # height, width, colour channels

# Permute the original tensor to rearrange the axis (or dimension) order
x_permuted = x_original.permute(2, 0, 1)  # colour channels, height, width (shifts axis 0->1, 1->2, 2->0)

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [182]:
x_original[0, 0, 0] = 9985
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(9985.), tensor(9985.))

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [183]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [184]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [185]:
# Let's index on the middle bracket (dim=1)
x[0][0], x[0, 0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [186]:
# Let's index on the most inner bracket (last dim)
x[0][0][0]

tensor(1)

In [187]:
x[0][0][1]

tensor(2)

In [189]:
x[0][1][1]

tensor(5)

In [190]:
x[0][2][2]

tensor(9)

In [191]:
# You can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [194]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [195]:
# Get all values of the 0th dimension but only the 1st index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [196]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [201]:
# Index on x to return 9
x[:, 2, 2], x[0][2][2]

(tensor([9]), tensor(9))

In [202]:
# Index on x to return 3, 6, 9
x[:, :, 2]

tensor([[3, 6, 9]])

## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.
And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`  
* PyTorch tensor -> NumPy : `torch.Tensor.numpy()`


In [212]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)  # warning: when converting from NumPy to PyTorch, PyTorch reflects NumPy's default datatype of float64 unless specified otherwise.
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [213]:
array.dtype

dtype('float64')

In [214]:
tensor.dtype

torch.float64

In [215]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [216]:
# Change the value of array, what will this do to `tensor`?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [217]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [218]:
numpy_tensor.dtype

dtype('float32')

In [219]:
# Change the tensor, what happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take the random out of random)

In short, how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again ...`

To reduce the randomness in neural networks in PyTorch comes the concept of a **random seed**.

What the random seed does is "flavour" the randomness.

In [220]:
torch.rand(3, 3)

tensor([[0.2933, 0.0610, 0.2335],
        [0.6816, 0.2098, 0.0806],
        [0.3735, 0.7680, 0.1604]])

In [221]:
torch.rand(3, 3)

tensor([[0.7629, 0.0478, 0.8183],
        [0.1420, 0.8627, 0.2693],
        [0.3785, 0.3714, 0.5974]])

In [222]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[7.3358e-01, 2.6943e-01, 2.2258e-01, 3.1992e-01],
        [1.1027e-04, 7.7704e-01, 6.6067e-01, 9.6797e-01],
        [5.6954e-01, 4.4305e-01, 6.9693e-01, 7.0662e-01]])
tensor([[0.5261, 0.4559, 0.8471, 0.0013],
        [0.0124, 0.1901, 0.1349, 0.6703],
        [0.3166, 0.0220, 0.2343, 0.1672]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [228]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42

# Create some random tensors
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on number, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory.

### 1. Getting a GPU

1. Easiest - use Google Colab for a free GPU (options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there's lots of options
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

For 2, 3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documentation.

To get a GPU on Google Colab: Execution > Change execution type > GPU

In [1]:
!nvidia-smi

Tue Feb 25 16:17:51 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   57C    P8             11W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

### 2. Check for GPU access with PyTorch

In [2]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code.

e.g. run on GPU if available, else default to CPU

In [7]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"

In [3]:
# Count the number of devices
torch.cuda.device_count()

1

## 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because a GPU results in faster computations.

In [5]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3], device="cpu")

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [6]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [8]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)  # won't error out whether or not a GPU is available
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [9]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [11]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [12]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

## Exercices & extra-curriculum

https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises

In [1]:
import torch

# Exercise 2

tensor = torch.rand(7, 7)
tensor, tensor.shape

(tensor([[0.8599, 0.2922, 0.5218, 0.7072, 0.2226, 0.9150, 0.8535],
         [0.2776, 0.7980, 0.2086, 0.0358, 0.8730, 0.7083, 0.7666],
         [0.7279, 0.3946, 0.2622, 0.5929, 0.3798, 0.4973, 0.4321],
         [0.7322, 0.8534, 0.9016, 0.5082, 0.6971, 0.6557, 0.3698],
         [0.0485, 0.3229, 0.9604, 0.9939, 0.0430, 0.9922, 0.2631],
         [0.2142, 0.4080, 0.6812, 0.3632, 0.0193, 0.3554, 0.9915],
         [0.9925, 0.8935, 0.6202, 0.1290, 0.6325, 0.2674, 0.0434]]),
 torch.Size([7, 7]))

In [16]:
# Exercise 3

tensor_B = torch.rand(1, 7)
tensor_B, tensor_B.shape

(tensor([[0.6087, 0.8472, 0.5070, 0.9101, 0.6631, 0.1133, 0.8848]]),
 torch.Size([1, 7]))

In [19]:
torch.matmul(tensor, tensor_B.T)

tensor([[1.3893],
        [2.4306],
        [2.6559],
        [1.7737],
        [1.9569],
        [2.4124],
        [2.2808]])

In [4]:
# Exercice 4
MANUAL_SEED = 0

torch.manual_seed(MANUAL_SEED)
tensor_A = torch.rand(7, 7)

torch.manual_seed(MANUAL_SEED)
tensor_B = torch.rand(1, 7)

torch.matmul(tensor_A, tensor_B.T)

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

In [3]:
# Exercise 5
import torch
torch.cuda.manual_seed(1234)

In [5]:
# Exercise 6

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"device: {device}")

torch.cuda.manual_seed(1234)
tensor_1_on_gpu = torch.rand(size=(2, 3)).to(device)

torch.cuda.manual_seed(1234)
tensor_2_on_gpu = torch.rand(size=(2, 3)).to(device)

tensor_1_on_gpu, tensor_2_on_gpu

device: cuda


(tensor([[0.3953, 0.1217, 0.9900],
         [0.9773, 0.5107, 0.4438]], device='cuda:0'),
 tensor([[0.6056, 0.3068, 0.8002],
         [0.0654, 0.4596, 0.5324]], device='cuda:0'))

In [10]:
# Exercise 7

print(tensor_1_on_gpu.shape)
print(tensor_2_on_gpu.shape)

tensor_3_on_gpu = torch.matmul(tensor_1_on_gpu, tensor_2_on_gpu.T)
tensor_3_on_gpu

torch.Size([2, 3])
torch.Size([2, 3])


tensor([[1.0690, 0.6088],
        [1.1037, 0.5349]], device='cuda:0')

In [12]:
# Exercise 8

print(f"Minimum value for tensor_3: {torch.min(tensor_3_on_gpu)}")
print(f"Maximum value for tensor_3: {torch.max(tensor_3_on_gpu)}")

Minimum value for tensor_3: 0.5348510146141052
Maximum value for tensor_3: 1.1036733388900757


In [13]:
# Exercise 9

print(f"Minimum index value for tensor_3: {torch.argmin(tensor_3_on_gpu)}")
print(f"Maximum index value for tensor_3: {torch.argmax(tensor_3_on_gpu)}")

Minimum index value for tensor_3: 3
Maximum index value for tensor_3: 2


In [16]:
# Exercise 10

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"device: {device}")

torch.cuda.manual_seed(7)
tensor_4_on_gpu = torch.rand(size=(1, 1, 1, 10)).to(device)
print(tensor_4_on_gpu, tensor_4_on_gpu.shape)

tensor_4_on_gpu_squeezed = torch.squeeze(tensor_4_on_gpu)
print(tensor_4_on_gpu_squeezed, tensor_4_on_gpu_squeezed.shape)

device: cuda
tensor([[[[0.5452, 0.7124, 0.3522, 0.2699, 0.3530, 0.1087, 0.8926, 0.3372,
           0.1418, 0.4584]]]], device='cuda:0') torch.Size([1, 1, 1, 10])
tensor([0.5452, 0.7124, 0.3522, 0.2699, 0.3530, 0.1087, 0.8926, 0.3372, 0.1418,
        0.4584], device='cuda:0') torch.Size([10])
